### ISSUE TITLE
Cannot save  "Set API Keys and Model" menu after inputing my OpenAI API key.

### ISSUE THREAD

**Issue by chama96825** [5TFG4/uCertify-Hero#1]
Thank you for creating this project. I followed the steps and saw the script active when I was in uCertify page. But I cannot save  "Set API Keys and Model" menu after inputing my OpenAI API key. Can you help take a look? And if possible, can you explain what went wrong, so I could learn more about Javascript? Thanks

![Screen Shot 2024-07-31 at 1 46 22 AM](https://github.com/user-attachments/assets/83392e10-db78-434a-8ce3-6caa5f756e49)

**Comment by 5TFG4** [comment]
Thank you for bringing this issue to my attention! I’ve noticed that this can happen to some users, but unfortunately, I haven’t identified the exact cause yet. When I have time, I'll investigate further. Some users have reported that even though it shows the API key couldn’t be saved, it still works fine after input. Have you tried this?

**Comment by chama96825** [comment]
> Thank you for bringing this issue to my attention! I’ve noticed that this can happen to some users, but unfortunately, I haven’t identified the exact cause yet. When I have time, I'll investigate further. Some users have reported that even though it shows the API key couldn’t be saved, it still works fine after input. Have you tried this?

Glad to hear it works for other people. Unfortunately it always shows "no answer" in my case. I tried to clear cache and updated to latest chrome, still saw this issue. Thank you for responding, I will also try to investigate and learn more about javascript on my end.

**Comment by chama96825** [comment]
Hey after I used the 2.0 version, I didn't see this issue anymore. Thank you for the update!

**Comment by 5TFG4** [comment]
Glad to know it worked!
